name: CI-CD

on:
  push:
    branches: [ main ]  

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    # Login to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Build and push Docker image
    - name: Build Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: brainupgrade/request-logger:${{ github.sha}}

    # Test the deployment
    - name: Test
      run: |
        docker run -d --name logger -p 8080:8080 brainupgrade/request-logger:${{ github.sha}}
        curl -s localhost:8080/ | grep -q "OK"

    - name: Push to DockerHub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: brainupgrade/request-logger:${{ github.sha}}