# .github/workflows/build.yml

name: Build Project

on: [workflow_dispatch, pull_request]

jobs:
  call-reusable-workflow:
    uses: brainupgrade-in/github-workflows/.github/workflows/maven-build-reusable.yml@main
    with:
      java-version: '11'
